name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: build and test
    uses: NLnetLabs/.github/.github/workflows/rust-ci.yml@main
    with:
      rust_msrv: 1.71
      test_minimal_versions: true
